version: '2.2'
services:
  logstash:
      image: logstash:7.10.1
      depends_on:
        - elasticsearch
      environment:
        XPACK_MONITORING_ENABLED: "false"
        ES_HOST: "elasticsearch:9200"
      ports:
        - "5044:5044/udp"
      volumes:
        - ./deploy/logstash.conf:/config/logstash.conf:ro
      command: logstash -f /config/logstash.conf

  kibana:
    image: kibana:7.17.8
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.17.8
    environment:
      discovery.type: single-node
    expose:
      - "9200"
    volumes:
      - /tmp/esdata:/tmp/elasticsearch/data
